=== jamesjcook/pyactionmap/xml/actionmaps.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT ActionMaps (visible?,actionmap+)>
<!-- visible and map are NOT standard parts,
they're to help actionmapper understand what to do
These MAY cause complete failure to load in crysis as they're not standard. 
Might be able to get around that by cleverly removing them from user maps,
while keeping them in the default and/or templates.  -->
<!ELEMENT visible (map+)>
<!ELEMENT map ANY> 
<!ELEMENT actionmap (action+)>
<!ELEMENT action (key+)>
<!ELEMENT key EMPTY>

<!ATTLIST actionmap
name CDATA #REQUIRED
version CDATA #REQUIRED>

<!ATTLIST action
name CDATA #REQUIRED
display_name CDATA #IMPLIED
onPress CDATA #IMPLIED
onRelease CDATA #IMPLIED
onHold CDATA #IMPLIED
always CDATA #IMPLIED
noModifiers CDATA #IMPLIED
retriggerable CDATA #IMPLIED
consoleCmd CDATA #IMPLIED
>

<!ATTLIST key name CDATA #REQUIRED>

=== jamesjcook/pyactionmap/xml/example_user.xml
<?xml version="1.0" encoding="UTF8" ?>
<!DOCTYPE ActionMaps SYSTEM "actionmaps.dtd" >

<ActionMaps>
 <actionmap name="STOVL" version="20">
  <action name="xi_v_rotatepitch">
   <key name="xi_thumbry"/>
  </action>
  <action name="v_rotateWingVertical" onPress="1" onRelease="1" onHold="1">
   <key name="lctrl"/>
  </action>
  <action name="v_rotateWingHorizontal" onPress="1" onRelease="1" onHold="1">
   <key name="lshift"/>
  </action>
  <action name="xi_v_movex">
   <key name="xi_thumbrx"/>
  </action>
  <action name="xi_v_movey">
   <key name="xi_thumbly"/>
  </action>
  <action name="xi_v_rotateyaw">
   <key name="xi_thumblx"/>
  </action>
  <action name="v_rotateyaw">
   <key name="maxis_x"/>
   <key name="null"/>
  </action>
  <action name="v_rotateroll">
   <key name="null"/>
   <key name="null"/>
  </action>
  <action name="v_rotatepitch">
   <key name="maxis_y"/>
   <key name="null"/>
  </action>
  <action name="v_moveup" onPress="1" onRelease="1" retriggerable="1">
   <key name="w"/>
  </action>
  <action name="v_movedown" onPress="1" onRelease="1" retriggerable="1">
   <key name="s"/>
  </action>
  <action name="v_rollleft" onPress="1" onRelease="1">
   <key name="a"/>
   <key name="null"/>
  </action>
  <action name="v_rollright" onPress="1" onRelease="1">
   <key name="d"/>
   <key name="null"/>
  </action>
  <action name="v_pitchup" onPress="1" onRelease="1">
   <key name="space"/>
  </action>
  <action name="v_pitchdown" onPress="1" onRelease="1">
   <key name="lctrl"/>
  </action>
 </actionmap>
 <actionmap name="aerospace" version="20">
  <action name="xi_v_rotatepitch">
   <key name="null"/>
   <key name="null"/>
  </action>
  <action name="xi_v_movex">
   <key name="null"/>
   <key name="null"/>
  </action>
  <action name="xi_v_movey">
   <key name="null"/>
   <key name="null"/>
  </action>
  <action name="xi_v_rotateyaw">
   <key name="null"/>
   <key name="null"/>
  </action>
  <action name="xi_v_rotateroll">
   <key name="null"/>
   <key name="null"/>
  </action>
  <action name="v_rotateyaw">
   <key name="maxis_x"/>
   <key name="null"/>
  </action>
  <action name="v_rotateroll">
   <key name="null"/>
   <key name="null"/>
  </action>
  <action name="v_rotatepitch">
   <key name="maxis_y"/>
   <key name="null"/>
  </action>
  <action name="v_moveup" onPress="1" onRelease="1" retriggerable="1">
   <key name="null"/>
   <key name="null"/>
  </action>
  <action name="v_movedown" onPress="1" onRelease="1" retriggerable="1">
   <key name="space"/>
   <key name="null"/>
  </action>
  <action name="v_turnleft" onPress="1" onRelease="1" onHold="1">
   <key name="null"/>
   <key name="null"/>
  </action>
  <action name="v_turnright" onPress="1" onRelease="1" onHold="1">
   <key name="null"/>
   <key name="null"/>
  </action>
  <action name="v_rollleft" onPress="1" onRelease="1">
   <key name="a"/>
   <key name="null"/>
  </action>
  <action name="v_rollright" onPress="1" onRelease="1">
   <key name="d"/>
   <key name="null"/>
  </action>
  <action name="ToggleGears" onPress="1">
   <key name="null"/>
   <key name="null"/>
  </action>
  <action name="v_pitchup" onPress="1" onRelease="1">
   <key name="w"/>
   <key name="null"/>
  </action>
  <action name="v_pitchdown" onPress="1" onRelease="1">
   <key name="s"/>
   <key name="null"/>
  </action>
  <action name="SetThrottleval">
   <key name="null"/>
   <key name="null"/>
  </action>
  <action name="levelout" onPress="1" onRelease="1">
   <key name="lctrl"/>
  </action>
 </actionmap>
 <actionmap name="debug" version="20">
  <action name="flymode" onPress="1" noModifiers="1">
   <key name="f3"/>
  </action>
  <action name="godmode" onPress="1" noModifiers="1">
   <key name="f4"/>
  </action>
  <action name="ulammo" onPress="1" noModifiers="1">
   <key name="np_2"/>
  </action>
  <action name="debug" onPress="1">
   <key name="7"/>
  </action>
  <action name="thirdperson" onPress="1" noModifiers="1">
   <key name="f1"/>
  </action>
  <action name="debug_ag_step" onPress="1">
   <key name="backslash"/>
  </action>
  <action name="tweak_enable" onPress="1">
   <key name="np_enter"/>
  </action>
  <action name="tweak_up" onPress="1">
   <key name="up"/>
   <key name="np_8"/>
  </action>
  <action name="tweak_down" onPress="1">
   <key name="down"/>
   <key name="np_2"/>
  </action>
  <action name="tweak_left" onPress="1">
   <key name="left"/>
   <key name="np_4"/>
  </action>
  <action name="tweak_right" onPress="1">
   <key name="right"/>
   <key name="np_6"/>
  </action>
  <action name="tweak_inc" onPress="1">
   <key name="np_add"/>
  </action>
  <action name="tweak_dec" onPress="1">
   <key name="np_subtract"/>
  </action>
 </actionmap>
 <actionmap name="default" version="20">
  <action name="xi_voice_chat_talk" onPress="1" onRelease="1">
   <key name="xi_b"/>
  </action>
  <action name="xi_hud_mouseclick" onPress="1" onRelease="1">
   <key name="xi_a"/>
  </action>
  <action name="next_spectator_target" onPress="1">
   <key name="right"/>
   <key name="mouse2"/>
  </action>
  <action name="prev_spectator_target" onPress="1">
   <key name="left"/>
  </action>
  <action name="cycle_spectator_mode" onPress="1">
   <key name="space"/>
  </action>
  <action name="hud_openteamchat" onPress="1">
   <key name="u"/>
  </action>
  <action name="hud_mousewheelup" onPress="1">
   <key name="mwheel_up"/>
  </action>
  <action name="hud_mousewheeldown" onPress="1">
   <key name="mwheel_down"/>
  </action>
  <action name="hud_mouserightbtndown" onPress="1">
   <key name="mouse2"/>
  </action>
  <action name="hud_mouserightbtnup" onRelease="1">
   <key name="mouse2"/>
  </action>
  <action name="hud_show_multiplayer_scoreboard" onPress="1">
   <key name="tab"/>
  </action>
  <action name="hud_hide_multiplayer_scoreboard" onRelease="1">
   <key name="tab"/>
  </action>
  <action name="hud_toggle_scoreboard_cursor" onPress="1" onRelease="1">
   <key name="space"/>
  </action>
  <action name="hud_show_pda_map" onPress="1">
   <key name="m"/>
  </action>
  <action name="xi_hud_show_pda_map" onPress="1" onRelease="1">
   <key name="xi_back"/>
  </action>
  <action name="hud_night_vision" onPress="1">
   <key name="i"/>
  </action>
  <action name="hud_mptutorial_disable" onPress="1">
   <key name="end"/>
  </action>
  <action name="track_enemy_surface" onPress="1" onRelease="1">
   <key name="null"/>
   <key name="xi_triggerl_btn"/>
  </action>
  <action name="track_previous_enemy_surface" onPress="1" onRelease="1">
   <key name="null"/>
   <key name="null"/>
  </action>
  <action name="track_previous_enemy_air" onPress="1" onRelease="1">
   <key name="null"/>
   <key name="null"/>
  </action>
  <action name="track_friendly_surface" onPress="1" onRelease="1">
   <key name="b"/>
   <key name="xi_start"/>
  </action>
  <action name="track_friendly_air" onPress="1" onRelease="1">
   <key name="null"/>
   <key name="null"/>
  </action>
  <action name="track_previous_friendly_surface" onPress="1" onRelease="1">
   <key name="v"/>
   <key name="null"/>
  </action>
  <action name="track_previous_friendly_air" onPress="1" onRelease="1">
   <key name="n"/>
   <key name="null"/>
  </action>
  <action name="track_nearest_enemy" onPress="1" onRelease="1">
   <key name="e"/>
   <key name="null"/>
  </action>
  <action name="track_next_enemy" onPress="1" onRelease="1">
   <key name="t"/>
   <key name="null"/>
  </action>
  <action name="track_previous_enemy" onPress="1" onRelease="1">
   <key name="null"/>
   <key name="null"/>
  </action>
  <action name="track_nearest_friendly" onPress="1" onRelease="1">
   <key name="null"/>
   <key name="null"/>
  </action>
  <action name="track_next_friendly" onPress="1" onRelease="1">
   <key name="null"/>
   <key name="null"/>
  </action>
  <action name="track_previous_friendly" onPress="1" onRelease="1">
   <key name="null"/>
   <key name="null"/>
  </action>
  <action name="toggle_radar_mode" onPress="1" onRelease="1">
   <key name="r"/>
   <key name="null"/>
  </action>
  <action name="specmovez">
   <key name="null"/>
   <key name="null"/>
  </action>
  <action name="specmovedown" onPress="1" onRelease="1" retriggerable="1">
   <key name="f"/>
   <key name="null"/>
  </action>
  <action name="specmoveup" onPress="1" onRelease="1" retriggerable="1">
   <key name="r"/>
   <key name="null"/>
  </action>
  <action name="attack1" onPress="1" onRelease="1">
   <key name="mouse1"/>
   <key name="null"/>
  </action>
  <action name="attack2" onPress="1" onRelease="1">
   <key name="mouse2"/>
   <key name="xi_shoulderr"/>
  </action>
  <action name="zoom" onPress="1" onRelease="1">
   <key name="z"/>
   <key name="null"/>
  </action>
  <action name="firemode" onPress="1">
   <key name="xi_dpad_up"/>
  </action>
  <action name="objectives" onPress="1">
   <key name="lbracket"/>
   <key name="null"/>
  </action>
  <action name="use" onPress="1" onRelease="1">
   <key name="f"/>
   <key name="null"/>
  </action>
  <action name="xi_use" onPress="1" onRelease="1">
   <key name="null"/>
   <key name="null"/>
  </action>
  <action name="voice_chat_talk" onPress="1" onRelease="1">
   <key name="v"/>
   <key name="null"/>
  </action>
  <action name="xi_zoom" onPress="1" onRelease="1">
   <key name="null"/>
   <key name="null"/>
  </action>
  <action name="xi_disconnect" onPress="1" onRelease="1">
   <key name="disconnect"/>
  </action>
  <action name="hud_mousex">
   <key name="maxis_x"/>
   <key name="xi_thumbrx"/>
  </action>
  <action name="hud_mousey">
   <key name="maxis_y"/>
   <key name="xi_thumbry"/>
  </action>
  <action name="hud_mouseclick" onPress="1" onRelease="1">
   <key name="mouse1"/>
  </action>
  <action name="hud_suit_menu" onPress="1" onRelease="1">
   <key name="mouse3"/>
  </action>
  <action name="hud_openchat" onPress="1">
   <key name="y"/>
  </action>
  <action name="hud_buy_weapons" onPress="1">
   <key name="comma"/>
   <key name="null"/>
  </action>
  <action name="hud_pda_scroll" onPress="1">
   <key name="backspace"/>
